// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgNy7Kzo4Trdf5tIb47Rd8W7A2WQzvAgc',
    appId: '1:633188443636:web:88c548a2105ef0dc15c5a1',
    messagingSenderId: '633188443636',
    projectId: 'bootcamp175-ec8fe',
    authDomain: 'bootcamp175-ec8fe.firebaseapp.com',
    storageBucket: 'bootcamp175-ec8fe.firebasestorage.app',
    measurementId: 'G-NHGLXHEQCT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDv5Vf197u8youRaI5FLwVIlUlpooWjcHg',
    appId: '1:633188443636:android:55fba623339e2b0015c5a1',
    messagingSenderId: '633188443636',
    projectId: 'bootcamp175-ec8fe',
    storageBucket: 'bootcamp175-ec8fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMJuCn4r2gk31dInl6UPLuk3Tx2GNz2iE',
    appId: '1:633188443636:ios:c2f28b387082a2e115c5a1',
    messagingSenderId: '633188443636',
    projectId: 'bootcamp175-ec8fe',
    storageBucket: 'bootcamp175-ec8fe.firebasestorage.app',
    iosBundleId: 'com.example.bootcamp175',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCMJuCn4r2gk31dInl6UPLuk3Tx2GNz2iE',
    appId: '1:633188443636:ios:c2f28b387082a2e115c5a1',
    messagingSenderId: '633188443636',
    projectId: 'bootcamp175-ec8fe',
    storageBucket: 'bootcamp175-ec8fe.firebasestorage.app',
    iosBundleId: 'com.example.bootcamp175',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBgNy7Kzo4Trdf5tIb47Rd8W7A2WQzvAgc',
    appId: '1:633188443636:web:bc0e056cb80103a515c5a1',
    messagingSenderId: '633188443636',
    projectId: 'bootcamp175-ec8fe',
    authDomain: 'bootcamp175-ec8fe.firebaseapp.com',
    storageBucket: 'bootcamp175-ec8fe.firebasestorage.app',
    measurementId: 'G-R17SMD01F6',
  );

}